auto: true
server: true
permalink: none
baseurl: "prose"
exclude:
- .gitignore
- README.md

prose:
  rooturl: "_posts"
  metadata: 
    _posts/articles: |
      published: true
      layout: article
      title: Title
      abstract: Description
      author_twitter: webcane
      author: webcane
      categories:
      - articles
